server.port: 8080
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 785445900
      max-request-size: 785445900
  liquibase:
    url: jdbc:postgresql://localhost:5433/uploader
    user: test
    password: testpass
  datasource:
    url: jdbc:postgresql://localhost:5433/uploader
    username: test
    password: testpass
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false


kafka:
  bootstrapAddress: localhost:9092
  producer-id: medicine_id
scraping:
  price-list: "Pricelims.aspx"
  host: "https://grls.rosminzdrav.ru/"
