version: '3.7'
services:
  postgres-tp:
    container_name: postgres_tp
    image: postgres:12.4
    environment:
      - POSTGRES_DB=batp_sale_points
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=testpass
      - PGDATA=/var/lib/postgresql/data/pgdata q
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  zookeeper-tp:
    container_name: zookeeper_tp
    image: docker.io/bitnami/zookeeper:3-debian-10
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-tp:
    container_name: kafka_tp
    image: docker.io/bitnami/kafka:2-debian-10
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-tp:2181
      - KAFKA_LISTENERS=INSIDE://kafka-tp:29092,OUTSIDE://kafka-tp:9092
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka-tp:29092,OUTSIDE://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
    depends_on:
      - zookeeper-tp
volumes:
  pgdata:
